### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by alextrastero** [dominikwilkowski/cfonts#3]
<img width="788" alt="screen shot 2017-04-11 at 11 33 10" src="https://cloud.githubusercontent.com/assets/4152819/24902502/abd517d8-1eaa-11e7-8e03-8e6b06c5a6da.png">

```
$ npm -v
3.8.6
$ node -v
v6.1.0
```

P.s. thanks for this cool CLI :)

**Comment by rubensdev** [comment]
Hi :),

I have the same problem:

cfonts
/opt/node/lib/node_modules/cfonts/node_modules/commander/index.js:289
  this.parent.on(this._name, listener);
             ^

TypeError: Cannot read property 'on' of undefined
    at Command.action (/opt/node/lib/node_modules/cfonts/node_modules/commander/index.js:289:14)
    at Object.<anonymous> (/opt/node/lib/node_modules/cfonts/bin/font.js:38:822)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
rubens@rbox:~ $ npm -v
3.10.8
rubens@rbox:~ $ node -v
v6.9.1

**Comment by dominikwilkowski** [comment]
I'll look into it folks. Hang in there!

**Comment by dominikwilkowski** [comment]
Fixed now hopefully :)
Published to `v1.1.2`. Let me know if you still have issues.

**Comment by rubensdev** [comment]
Yes, it's working now :+1:,

Thank you!

**Comment by alextrastero** [comment]
<img width="261" alt="screen shot 2017-04-12 at 11 06 35" src="https://cloud.githubusercontent.com/assets/4152819/24950100/1f5fdc86-1f70-11e7-9876-265b3c8fc4ac.png">
